### ISSUE TITLE
Comments on Cog Est Task

### ISSUE THREAD

**Issue by danieljwilson** [JuneOh710/cognitive-estimation-test#1]
## Launch

Opens on directory instead of starting task:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/7377893/156539671-cca48069-5050-4739-9ba4-f41371328aae.png">

## Intro Page
- [x] Narrower (50% screen width)
- [x] Slightly larger text
- [x] Each sentence on separate line

## Instructions
- [x] Narower (50% screen width)
- [x] Maybe a bit better user experience to have an actual button to click to continue?

## Task screens
- [x] Can you make the button blue to match the other tasks?
- [x] For this question I think that you should allow decimals as most ties are less than 1m...
<img width="646" alt="image" src="https://user-images.githubusercontent.com/7377893/156540244-b8d99b69-6328-4ab1-91eb-f8210ed4f98c.png">

## Task Completion
- [x] Just seems to end on a blank screen?
